spring:
  application:
    name: "discoveryserver"
  config:
    import: "optional:configserver:http://localhost:8888/"

server:
  port: 8761

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"
    register-with-eureka: false
    fetch-registry: false

