global:
  scrape_interval: 15s

rule_files:
  - "/etc/prometheus/alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  - job_name: "configserver-app"
    scrape_interval: 30s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["configserver:8888"]

  - job_name: "discoveryserver-app"
    scrape_interval: 30s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["discoveryserver:8761"]

  - job_name: "gatewayserver-app"
    scrape_interval: 30s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["gatewayserver:8072"]

  - job_name: "analyticservice-app"
    scrape_interval: 30s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["analyticservice:8080"]

  - job_name: "billingpaymentservice-app"
    scrape_interval: 30s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["billingpaymentservice:8081"]

  - job_name: "contractservice-app"
    scrape_interval: 30s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["contractservice:8082"]

  - job_name: "customerservice-app"
    scrape_interval: 30s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["customerservice:8083"]

  - job_name: "customersupportservice-app"
    scrape_interval: 30s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["customersupportservice:8084"]

  - job_name: "notificationservice-app"
    scrape_interval: 30s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["notificationservice:8085"]

  - job_name: "planservice-app"
    scrape_interval: 30s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["planservice:8086"]

  - job_name: "userservice-app"
    scrape_interval: 30s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["userservice:8087"]