global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "configserver-app"
    scrape_interval: 30s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["configserver:8888"]