spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8888/"
  cloud:
    gateway:
      routes:
        - id: "customerservice"
          uri: "lb://customerservice"
          predicates:
            - "Path=/api/v1/**"

server:
  port: 8072

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"
    register-with-eureka: true
    fetch-registry: true
