
package com.turkcell.customerservice.outservices.mernis;
//------------------------------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 9.3.3.2
//
// Created by Quasar Development 
//
// This class has been generated for test purposes only and cannot be used in any commercial project.
// To use it in commercial project, you need to generate this class again with Premium account.
// Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
//
// Licence: A2F1EE67251196CB9AE51919EA06EB20A1FCE35AAF9E7541FD2D7400525B0FAA3A2DFD7F3201633933C56F36720993FE4AF02467B2A130DCDF43CDD49FBABC5A
//------------------------------------------------------------------------
import java.net.URL;
import java.io.*;
import java.net.HttpURLConnection;
import java.util.HashMap;
import java.util.Map;
import java.util.List;

public interface IMGConnectionProvider
{
    IMGResponseData sendRequest(String url,String requestBody,HashMap< String,String> httpHeaders, IMGRequestResultHandler handler,String contentType) throws java.lang.Exception;
}

class IMGHttpConnectionProvider implements IMGConnectionProvider{

    public void prepareRequest(HttpURLConnection url,String requestBody, IMGRequestResultHandler handler,String contentType ) throws java.lang.Exception {
        OutputStreamWriter wr = new OutputStreamWriter(url.getOutputStream());
        wr.write(requestBody);
        wr.flush();
    }

    @Override
    public IMGResponseData sendRequest(String url,String requestBody, HashMap< String, String> httpHeaders,IMGRequestResultHandler handler,String contentType ) throws java.lang.Exception
    {
        URL urlObject=new URL(url);
        HttpURLConnection connection=(HttpURLConnection)urlObject.openConnection();
        connection.setRequestMethod("POST");
        for(Map.Entry<String, String> entry : httpHeaders.entrySet())
        {
            connection.setRequestProperty(entry.getKey(),entry.getValue());
        }
        connection.setRequestProperty("user-agent","https://easyWSDL.com Generator 9.3.3.2");
        prepareRequest(connection,requestBody,handler, contentType );


        IMGResponseData response=new IMGResponseData();
        for(Map.Entry<String, List<String>> entry : connection.getHeaderFields().entrySet())
        {
            if(entry.getKey()!=null)
            {
                String values = "";
                for (String value : entry.getValue()) {
                    values = values + value;
                }
                response.getHeaders().put(entry.getKey(),values);
            }
        }
        
        try(InputStream dataStream = getResponseStream(connection,response,handler))
        {
            response.setBody(IMGHelper.streamToString(dataStream));
        }
        
        return response;
    }

    protected InputStream getResponseStream(
        HttpURLConnection url,
        IMGResponseData response,
        IMGRequestResultHandler handler
    ) throws java.lang.Exception
    {
        try{
            return url.getInputStream();
        }
        catch (IOException ex)
        {
            return url.getErrorStream();
        }
    }
}