
package com.turkcell.customerservice.outservices.mernis;

//------------------------------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 9.3.3.2
//
// Created by Quasar Development 
//
// This class has been generated for test purposes only and cannot be used in any commercial project.
// To use it in commercial project, you need to generate this class again with Premium account.
// Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
//
// Licence: A2F1EE67251196CB9AE51919EA06EB20A1FCE35AAF9E7541FD2D7400525B0FAA3A2DFD7F3201633933C56F36720993FE4AF02467B2A130DCDF43CDD49FBABC5A
//------------------------------------------------------------------------
public interface IMGDateTimeParser
{
    String getStringFromDateTime(java.time.ZonedDateTime date);
    String getStringFromDate(java.time.LocalDate date);
    String getStringFromTime(java.time.LocalTime date);
    String getStringFromDuration(java.time.Duration date);
    java.time.ZonedDateTime parse(String value);
    java.time.LocalDate parseLocal(String value);
    java.time.Duration parseDuration(String value);
    java.time.LocalTime parseTime(String value);
}
