spring:
  application:
    name: "customersupportservice"
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    config:
      profile: local
    stream:
      defaultBinder: kafka
      function:
        definition: ticketCreatedFunction
      bindings:
        ticketCreatedFunction-out-0:
          destination: ticket-topic
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092
  config:
    import: "optional:configserver:http://localhost:8888/"
