spring:
  application:
    name: "customersupportservice"
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    config:
      profile: local
  config:
    import: "optional:configserver:http://localhost:8888/"
