spring:
  application:
    name: "customersupportservice"
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27018/customersupportservice?authSource=admin
  config:
    import: "optional:configserver:http://localhost:8888/"

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"
    register-with-eureka: true
    fetch-registry: true
