spring:
  application:
    name: "configserver"
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/ErtanSidar/turkcell-crm-project-configs.git"
          default-label: main

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
#  tracing:
#    sampling:
#      probability: 1.0
#  zipkin:
#    tracing:
#      endpoint: "http://localhost:9411/api/v2/spans"
  metrics:
    export:
      prometheus:
        enabled: true
