spring:
  application:
    name: "analyticservice"
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/analyticservice?authSource=admin
  profiles:
    active: dev
  config:
    import: "optional:configserver:http://localhost:8888/"
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"
    register-with-eureka: true
    fetch-registry: true
