spring:
  application:
    name: "analyticservice"
  profiles:
    active: mongo
  cloud:
    config:
      profile: local
  config:
    import: "optional:configserver:http://localhost:8888/"
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
