spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
  application:
    name: "userservice"
  profiles:
    active: jpa
  cloud:
    config:
      profile: local
  config:
    import: "optional:configserver:http://localhost:8888/"

#  data:
#    redis:
#      host: localhost
#      port: 6379
#      password:
#      timeout: 5000
#      client-type: lettuce
#      lettuce:
#        pool:
#          max-active: 10
#          max-wait: 2000ms
#          max-idle: 5
#          min-idle: 2
#      database: 0





