spring:
  application:
    name: "userservice"
  config:
    import: "optional:configserver:http://localhost:8888/"
  datasource:
    url: jdbc:postgresql://localhost:5435/userservice
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8087

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"
    register-with-eureka: true
    fetch-registry: true
jwt:
  expiration: 600000
  secret: "NF20U4dirMhJFuK7G7iXxNFNa6qt6FWVbZL5e5fjufvvhFS6SJSSlgZ0O8UxUneKDJpOSzDZ4WWppe0fS1K1ETSvV2nK1qEioHwaJwTbw04fRDk"





