spring:
  application:
    name: "notificationservice"
  config:
    import: "optional:configserver:http://localhost:8888/"

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"
    register-with-eureka: true
    fetch-registry: true
