apiVersion: v1
kind: Service
metadata:
  name: user-service-db-service
  labels:
    app: user-service-db
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30008 # 30000 and 32767
  selector:
    app: user-service-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-service-db-pvc
  labels:
    app: user-service-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-db
  labels:
    app: user-service-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service-db
  template:
    metadata:
      labels:
        app: user-service-db
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: user-service-db-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: user-service-db-storage
      volumes:
        - name: user-service-db-storage
          persistentVolumeClaim:
            claimName: user-service-db-pvc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-db-config
  labels:
    app: user-service-db
data:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_DB: "userservice"