spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
  application:
    name: "planservice"
  profiles:
    active: jpa
  cloud:
    config:
      profile: local
  config:
    import: "optional:configserver:http://localhost:8888/"




