name: Spring Boot Microservices Project CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [
          analyticservice,
          billingpaymentservice,
          configserver,
          contractservice,
          customerservice,
          customersupportservice,
          discoveryserver,
          gatewayserver,
          notificationservice,
          planservice,
          userservice
        ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven

      - name: Build Common Module
        run: mvn clean install -DskipTests
        working-directory: common

      - name: Build with Maven
        working-directory: ${{matrix.service}}
        run: mvn clean package -DskipTests

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER_NAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: ${{matrix.service}}
          file: ${{matrix.service}}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USER_NAME }}/${{ matrix.service }}:latest