name: Spring Boot Microservices Project CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
  DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [configserver, discoveryserver, gatewayserver]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven

      - name: Build with Maven
        working-directory: ${{matrix.service}}
        run: mvn clean package -DskipTests

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: ${{matrix.service}}
          file: ${{matrix.service}}/Dockerfile
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/${{ matrix.service }}:latest


#      - name: Build and push Docker images
#        working-directory: ${{matrix.service}}
#        run: |
#          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest .
#
#      - name: Docker Push
#        run: |
#          docker push ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest
