name: Qodana Local Scan
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Run Qodana Docker Scan'
        run: |
          docker run --rm -v $(pwd):/project jetbrains/qodana-jvm:2024.3
