name: SonarQube

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [
          analyticservice,
          billingpaymentservice,
          configserver,
          contractservice,
          customerservice,
          customersupportservice,
          discoveryserver,
          gatewayserver,
          notificationservice,
          planservice,
          userservice
        ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build Common Module
        run: mvn clean install -DskipTests
        working-directory: common

      - name: Build and analyze - ${{ matrix.service }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn clean install -DskipTests && mvn sonar:sonar -Dsonar.projectKey=ErtanSidar_turkcell-crm-project
        working-directory: ${{ matrix.service }}
