name: Sonar Scan
on:
  push:
    branches:
        - main
  workflow_dispatch:

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [
          analyticservice,
          billingpaymentservice,
          configserver,
          contractservice,
          customerservice,
          customersupportservice,
          discoveryserver,
          gatewayserver,
          notificationservice,
          planservice,
          userservice
        ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Build Common Module
        run: mvn clean install -DskipTests
        working-directory: common

      - name: Build with Maven
        working-directory: ${{matrix.service}}
        run: mvn clean package -DskipTests

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        with:
          projectBaseDir: ${{matrix.service}}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: 'https://sonarcloud.io/'